### ISSUE TITLE
django.db.utils.OperationalError: (1045, "Access denied for user 'username'@'localhost' (using password: YES)")

### ISSUE THREAD

**Issue by AYeshwanth** [sorz/isi#1]
After running the command
python manage.py runserver

I am getting the following error

django.db.utils.OperationalError: (1045, "Access denied for user 'username'@'localhost' (using password: YES)")

**Comment by sorz** [comment]
You need configure the database connection on `store/store/settings/config.py`.
In the sample config file, it use MySQL on localhost. You may just comment it out  to use SQLite simply.

**Comment by AYeshwanth** [comment]
Thanks a lot...!
