### ISSUE TITLE
ImportError: No module named django.core.management

### ISSUE THREAD

**Issue by AYeshwanth** [sorz/isi#2]
when I am running the command 
python manage.py bower install

I am getting this error, pls do help...
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management

**Comment by sorz** [comment]
Did you install all the requirements with `pip install -r requirements.txt`?

**Comment by AYeshwanth** [comment]
yeah
I have done that.......

**Comment by AYeshwanth** [comment]
I have redone all the steps again and this error didn't come thanks anyways mate.
