### ISSUE TITLE
TypeError at /category/ super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by AYeshwanth** [sorz/isi#3]
When I click on Category button or rgister button I am getting such errors......

these are the traceback errors : 

Environment:
Request Method: GET
Request URL: http://127.0.0.1:8000/category/

Django Version: 1.8
Python Version: 2.7.12
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'sorl.thumbnail',
 'djangobower',
 'bootstrap3',
 'store',
 'product',
 'category',
 'cart',
 'order',
 'account',
 'admin',
 'category_admin',
 'product_admin',
 'account_admin',
 'order_admin')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py" in dispatch
  89.         return handler(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py" in get
  158.         context = self.get_context_data(**kwargs)
File "/home/yeshwanth/ISISTORE/isi/store/category/views.py" in get_context_data
  19.         context = super().get_context_data(**kwargs)

Exception Type: TypeError at /category/
Exception Value: super() takes at least 1 argument (0 given)

**Comment by sorz** [comment]
Not support for Python 2.
